# Generated by Django 3.2.13 on 2022-06-07 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20220604_1610'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
